export const Bengali = [
    { id: 'b_new_1', title: "Ghum Ghum Chand Jhikimiki Tara | Male Version | Romantic Bengali Song", artist: "Ayan Studio", ytId: 'd-B29nCwtEE', lyrics: "" },
    { id: 'b_new_2', title: "Khawne Gorachand, Khawne Kaalaa | লহ গৌরাঙ্গের নাম রে | Arijit Singh | ID | Ritam | Srijit | SVF,DCM", artist: "SVF", ytId: 'guv_YlxJIHo', lyrics: "" },
    { id: 'b_new_3', title: "Borne gondhe Chande gitite | বর্ণে গন্ধে । Tumi Shudhu Tumi | Rishi Panda cover", artist: "Rishi Panda", ytId: 'r88ZgrQPTbQ', lyrics: "" },
    { id: 'b_new_4', title: "Jawl Phoring 2.0 (জল ফড়িং 2.0) | Prem Tame | Anupam Roy | Soumya, Susmita, Sweta | Anindya | SVF", artist: "SVF", ytId: 'qMPqnA8kjT0', lyrics: "" },
    { id: 'b_new_5', title: "Gulbahar | গুলবাহার | Ishaan এর Gaan | Shuvendu Das Shuvo | Official Music Video", artist: "Ishaan এর Gaan ", ytId: 'Ib_L3vuUX5k', lyrics: "" },
    { id: 'b_new_6', title: "\"Jodi Abar\" ( যদি আবার ) OFFICIAL MUSIC VIDEO | Angel Noor |Bangla new song 2024.", artist: "Angel Noor", ytId: 't99Z5ym-nJY', lyrics: "" },
    { id: 'b_new_7', title: "Ei To Hethay Kunja Chhayay | Unplugged Version | Bengali Acoustic Love Song", artist: "Ayan Studio", ytId: '7IKvK2x16aY', lyrics: "" },
    { id: 'b_new_8', title: "Kichhu Kichhu Kotha |( কিছু কিছু কথা )| Arijit & Kaushiki | Bipul Mondal | New Lyrical Song 2025", artist: "ABACUS ORIGINALS", ytId: 'XXNbzwbepWw', lyrics: "" },
    { id: 'b_new_9', title: "Ki Name Deke Bolbo Tomake | Miftah Zaman | Latest Bengali Cover Song 2022", artist: "Saregama Open Stage", ytId: '7UbpNPb255k', lyrics: "" },
    { id: 'b_new_10', title: "Baundule Ghuri (বাউন্ডুলে ঘুড়ি) - Reprise By @AnupamRoy | New Bengali Song | SVF Music", artist: "SVF Music", ytId: '1reZByeUhPY', lyrics: "" },
    { id: 'b_new_11', title: "Tumi Bristi Cheyecho Bole | ( তুমি বৃষ্টি চেয়েছো বলে ) | Mahtim sakib | New Lyrical Song 2024", artist: "ABACUS ORIGINALS", ytId: '4vPKLGz0bU4', lyrics: "" },
    { id: 'b_new_12', title: "চল রাস্তায় সাজি ট্রাম লাইন l Chal Rastay Saaji Tram Line l Shreya Ghoshal l Lyrics", artist: "Music BD", ytId: 'fILC1AqOM_k', lyrics: "" },
    { id: 'b_new_13', title: "Unknown Title", artist: "Unknown Artist", ytId: 'u2UHKKiqqOA', lyrics: "" },
    { id: 'b_new_14', title: "Bulbuli | Coke Studio Bangla | Season One | Ritu Raj X Nandita", artist: "Coke Studio Bangla", ytId: '9c1NIrAqXe4', lyrics: "" },
    { id: 'b_new_15', title: "Benche Thakar Gaan (বেঁচে থাকার গান) | Lyrical | Autograph | Prosenjit | Rupam Islam | Srijit", artist: "SVF Music", ytId: 'ep52mT-w_TI', lyrics: "" },
    { id: 'b_new_16', title: "MAJHEY MAJHEY TOBO - TAPOSH FEAT. MAHTIM SHAKIB : OMZ WIND OF CHANGE [ S:06 ]", artist: "Gaan Bangla TV", ytId: 'QZYDmwpVDGs', lyrics: "" },
    { id: 'b_new_17', title: "'Moner Manush' - Anupam Roy Feat. Satyaki Banerjee & Babul Supriyo - Coke Studio@MTV Season 4", artist: "Coke Studio India ", ytId: 'o5iNbmDbViA', lyrics: "" },
    { id: 'b_new_18', title: "Porer Jaga Porer Jomin  || IPDC আমাদের গান || Joler Gaan", artist: "IPDC আমাদের গান", ytId: 'jqf8BDOYles', lyrics: "" },
    { id: 'b_new_19', title: "Behag Jodi Na Hoi Raji | Unplugged Version | Bengali Classical Song", artist: "Ayan Studio", ytId: 'uhhdKNAWnfM', lyrics: "" },
    { id: 'b_new_20', title: "Rishi Panda Jukebox | Bengali Covers", artist: "Rishi Panda", ytId: 'gMbmvRj0j7E', lyrics: "" },
    { id: 'b_new_21', title: "BEST OF FOSSILS SONG BY RUPAM ISLAM 🔥|| TOP 10 BEST BENGALI SONG || ROCKING WORLD", artist: "Rocking World", ytId: 'enAHzgM3J2M', lyrics: "" },
    { id: 'b_new_22', title: "KOMOLA - Ankita Bhattacharyya | Bengali Folk Song | Music Video 2021| Dance", artist: "Ankita Bhattacharyya", ytId: '5f1O74GwWJM', lyrics: "" },
    { id: 'b_new_23', title: "RANGABATI | GOTRO | SUROJIT | IMAN | OM | MANALI | DEVLINA | NIGEL | Bengali Film Song 2019", artist: "Times Music Bangla", ytId: 'IU340-JBKA4', lyrics: "" },
    { id: 'b_new_24', title: "Dugga Elo - Official Video | Monali Thakur | Guddu | Indranil Das", artist: "Zee Music Bangla", ytId: 'xlElO06nQy8', lyrics: "" },
    { id: 'b_new_25', title: "Krishna Bole ( কৃষ্ণ বলে ) | Pousali Banerjee | Bhajan Song | Aalo", artist: "Aalo | আলো 🪔", ytId: 'sn4ok8KAoKQ', lyrics: "" },
    { id: 'b_new_26', title: "Hare Krishna | The Power of Devotional Music rediscovered by FAKIRA", artist: "Fakira", ytId: 'YA0fzrnKmCs', lyrics: "" },
    { id: 'b_new_27', title: "\"Mon Re Krisikaj\" Official Video|Manobjomin| @OriyonMusicByArijitSingh |Joy S.|Ramprasadi| Srijato", artist: "Sony Music Bangla", ytId: 'NWKDbecvheo', lyrics: "" },
    { id: 'b_new_28', title: "O Shyama - ও শ্যামা | Satyaki Banerjee | Avishek Saha | Bengali Folk Devotional Song | Beats Music", artist: "Beats", ytId: 'VwibjuKHO0c', lyrics: "" },
    { id: 'b_new_29', title: "MEERA - Rahul Dutta | Supratip B | Sreetama | Official Music Video | Bengali New Sad Song 2021", artist: "Rahul Dutta", ytId: 'cLizhImPFyQ', lyrics: "" },
    { id: 'b_new_30', title: "Shrikrishno Kirton | Aditi Munshi | Manali |  Gotro | Krishna Nam | Latest Bengali Song", artist: "Times Music Bangla", ytId: 'C8_VfjZI-OY', lyrics: "" },
    { id: 'b_new_31', title: "Dekhechhi Rupshagore (দেখেছি রূপসাগরে) | Mahtim Shakib | Arindom | Ditipriya,Dibyojyoti | SVF Music", artist: "SVF Music", ytId: 'ReBHEyAd2zk', lyrics: "" },
    { id: 'b_new_32', title: "Majhe Majhe Tobo (মাঝে মাঝে তব ) | Prashmita Paul | Rabindra Sangeet | Aalo", artist: "Aalo | আলো 🪔", ytId: 'XOuc-oVSOnw', lyrics: "" },
    { id: 'b_new_33', title: "Hey Shokha (হে সখা) | Rabindrasangeet | Somlata | Arindom | Anushka, Dibyojyoti | SVF Music", artist: "SVF Music", ytId: 'UpxTJXxTJJ0', lyrics: "" },
    { id: 'b_new_34', title: "Tomra Kunjo Sajao Go (তোমরা কুঞ্জ সাজাও গো) | HD Video Song | Krishnakoli (Zee Bangla)", artist: "YouVik", ytId: '8ysq4DK-mpQ', lyrics: "" },
    { id: 'b_new_35', title: "Dub De Re Mon Kali Bole (ডুব দে রে মন কালী বলে) | Arpita Dey | Maa Kali Song | Aalo", artist: "Aalo | আলো 🪔", ytId: 'NsZa2_zNp7o', lyrics: "" },
    { id: 'b_new_36', title: "DHAK BAJA KASHOR BAJA Video Song || Shreya Ghoshal || Jeet Gannguli || Durga Puja Special Songs", artist: "T-Series", ytId: 'id5_3dKvEBg', lyrics: "" },
    { id: 'b_new_37', title: "Shyama Sangeet | সেরা ২০টি শ্যামা সংগীত | Kali Puja Song Bengali | Kumar Sanu |Anuradha Paudwal 2024", artist: "sudhamoy karmakar", ytId: 'R7f_Kk8P8XY', lyrics: "" },
    { id: 'b_new_38', title: "Aro Ekber | Fossils | Audio Song | Rupam Islam", artist: "Asha Audio", ytId: 'T71ZyjvCtOA', lyrics: "" },
    { id: 'b_new_39', title: "Neel Rang Bhison Priyo | Audio | Rupam Islam", artist: "Saregama Bengali", ytId: 'eKH-mHSL8Zo', lyrics: "" },
    { id: 'b_new_40', title: "De De Pal Tule De | Fakira Live | Ft. Timir Biswas", artist: "ASHIRBAD STUDIO", ytId: 'UhZbjnnzcG4', lyrics: "" },
    { id: 'b_new_41', title: "Ja Pakhi Urte Dilam Toke - Silajit | Lyrical | যা পাখি | New Lyrical Bengali Song 2023 | Shemaroo", artist: "Shemaroo Bengali Music", ytId: 'L2Z0Y-vTQNc', lyrics: "" },
    { id: 'b_new_42', title: "Ek Minute Er Chumu (এক মিনিটের চুমু) | Bengali Music Video | Debraj,Anirban,Subhadeep | Hooligaanism", artist: "HooliGaanism", ytId: 'i7gj9xogbR0', lyrics: "" },
    { id: 'b_new_43', title: "Rabindra Sangeet | O Je Mane Na Mana | Somlata Acharyya Chowdhury | Somlata And The Aces |", artist: "Somlata Acharyya Chowdhury", ytId: 'J03Ts-HdzGI', lyrics: "" },
    { id: 'b_new_44', title: "Arijit Singh Romantic Hits LIVE | Audio Jukebox | Bengali Romantic Hits | SVF Music", artist: "SVF Music", ytId: 'ekmv-O0UulE', lyrics: "" },
    { id: 'b_new_45', title: "60's Classic Bangla Hits | Manna Dey | Kishore Kumar | Hemanta Mukherjee | Lata Mangeshkar", artist: "Saregama Bengali", ytId: 'e90alqXR9dM', lyrics: "" },
    { id: 'b_new_46', title: "OLIRO KOTHA SHUNE | Debolinaa Nandy | Sayak Chakraborty | Hemanta Mukherjee | Bengali Cover", artist: "Debolina Nandy", ytId: 'XpYWLmtvvII', lyrics: "" },
];