export const English = [
    { id: 'e_new_1', title: "Ed Sheeran - Sapphire (Official Music Video)", artist: "Ed Sheeran", ytId: 'JgDNFQ2RaLQ', lyrics: "" },
    { id: 'e_new_2', title: "Ellie Goulding - Love Me Like You Do (Lyrics)", artist: "Twilight Sounds ", ytId: 'JrNMyzsYr4M', lyrics: "" },
    { id: 'e_new_3', title: "Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song)", artist: "shakiraVEVO", ytId: 'pRpeEdMmmQ0', lyrics: "" },
    { id: 'e_new_4', title: "DJ Snake - Let Me Love You (Official Music Video) ft. Justin Bieber", artist: "DJSnakeVEVO", ytId: 'euCqAq6BRa4', lyrics: "" },
    { id: 'e_new_5', title: "Imagine Dragons - Believer (Lyrics)", artist: "7clouds", ytId: 'W0DM5lcj6mw', lyrics: "" },
    { id: 'e_new_6', title: "Ed Sheeran - Shape of You (Lyrics)", artist: "7clouds", ytId: 'liTfD88dbCo', lyrics: "" },
    { id: 'e_new_7', title: "Shakira & Burna Boy - Dai Dai (Lyrics) World Cup Song 2026", artist: "7clouds", ytId: 'salwJjShv2M', lyrics: "" },
    { id: 'e_new_8', title: "Justin Bieber - Baby ft. Ludacris", artist: "JustinBieberVEVO", ytId: 'kffacxfA7G4', lyrics: "" },
    { id: 'e_new_9', title: "Ed Sheeran - best of the best song collection", artist: "Syringe lyrics", ytId: 'HfoNNEA9MIE', lyrics: "" },
    { id: 'e_new_10', title: "Alec Benjamin - Let Me Down Slowly (Lyrics)", artist: "a paradise bird", ytId: 'jLNrvmXboj8', lyrics: "" },
    { id: 'e_new_11', title: "Chill Vibes English Songs💞|| Best Acoustic Love Songs | Spotify Trending Hits – Chill & Relax", artist: "Acoustic Pulse", ytId: '4lMKsUZZu3Y', lyrics: "" },
    { id: 'e_new_12', title: "🎧Top Hits Music Spotify 2026🌿|| New Popular English Songs --Latest Healing Music Spotify 2026", artist: "JsVibes Music", ytId: 'l2rbnKyHgho', lyrics: "" },
    { id: 'e_new_13', title: "🐻Trending Spotify Playlist 2026 ~ Healing English Songs🧡|| Acoustic Chill & Positive Vibes Music", artist: "JsVibes Music", ytId: 'a9VHDa9mOvY', lyrics: "" },
    { id: 'e_new_14', title: "Viral Pop Songs Cover 2026 🎙 Top Music Playlist Hits", artist: "Acoustic Therapy", ytId: 'JKRRl5-5-hw', lyrics: "" },
    { id: 'e_new_15', title: "🔝🎶Spotify Hits Music 2026 || Top Music Playlist -- Best 50 English Songs | Viral Tiktok Music", artist: "JsVibes Music", ytId: 'S1wiLj-JUCc', lyrics: "" },
    { id: 'e_new_16', title: "🩶Best 100 English Songs 2026 || Chill Vibes Playlist -- Easy Listening Spotify Music 2026", artist: "JsVibes Music", ytId: 'kRZs91of3c4', lyrics: "" },
    { id: 'e_new_17', title: "English Songs with Lyrics 2025 🌙 Acoustic Songs 2025 Latest Top Hits Love Playlist", artist: "Trendy Plus", ytId: 'WJBPc3IQD5g', lyrics: "" },
    { id: 'e_new_18', title: "🌸🟢Top 50 Global Music Spotify 2026 Playlist || Top Pop English Songs ~ Best Music Travel 2026", artist: "JsVibes Music", ytId: 'nesM9AGNoXk', lyrics: "" },
    { id: 'e_new_19', title: "Playlist make you feel like a gangster | Gentleman Songs (Vol.3)", artist: "Dark Blues Music", ytId: 'ww6N-jyjsbw', lyrics: "" },
    { id: 'e_new_20', title: "Ed Sheeran & Diljit Dosanjh - Shape of You x Naina (Live in Birmingham 2024)", artist: "Ed Sheeran", ytId: 'k0Ka-deab1s', lyrics: "" },
];