export const Hindi = [
    { id: 'h_new_1', title: "RAM SIYA RAM I Adipurush", artist: "Camshaft ", ytId: 'U63zW7fUhJw', lyrics: "" },
    { id: 'h_new_2', title: "Arijit Singh Songs | Hindi Love Songs | Arijit Singh Songs Playlist | Hindi Songs Collection", artist: "Tips Official", ytId: 'hMBdmu9fQvc', lyrics: "" },
    { id: 'h_new_3', title: "Namo Namo - Lyrical | Kedarnath | Sushant Rajput | Sara Ali Khan | Amit Trivedi | Amitabh B", artist: "Zee Music Company", ytId: 'dx4Teh-nv3A', lyrics: "" },
    { id: 'h_new_4', title: "Raataan Lambiyan - Lyric Video | Shershaah | Sidharth, Kiara | Tanishk B. | Jubin | Asees", artist: "Sony Music India", ytId: 'orYf6VDtj_k', lyrics: "" },
    { id: 'h_new_5', title: "LONG DRIVE Bollywood Mix - Arijit Singh | Full Album | 2 Hour Nonstop | Apna Bana Le, Zaalima & More", artist: "Bollywood Chartbusters", ytId: '00DvaPstcpo', lyrics: "" },
    { id: 'h_new_6', title: "Best of Atif Aslam Romantic Hits - Jukebox | Evergreen Songs Of Atif Aslam | Hindi Love Songs", artist: "Music Beats", ytId: 'K7o9fUEP3GU', lyrics: "" },
    { id: 'h_new_7', title: "Abhi Na Jao Chhodkar | World Music Day Concert 24 | Sourendro-Soumyojit", artist: "Sourendro Soumyojit", ytId: 'AB-I3vsUk6g', lyrics: "" },
    { id: 'h_new_8', title: "Shaky ( Official #Video ) Sanju Rathod Ft. Isha Malviya | G-Spark | New #Marathi Songs 2025", artist: "Sanju Rathod SR", ytId: 'sUf2PtEZris', lyrics: "" },
    { id: 'h_new_9', title: "Shreya Ghoshal Top 10 Songs | Best Of Shreya Ghoshal | Latest Bollywood Songs | Hindi Songs ", artist: "Hits Of Shreya ", ytId: 'pN--zyXztLI', lyrics: "" },
    { id: 'h_new_10', title: "Gehra Hua - Lyrical (Full Version) | Dhurandhar, Ranveer Singh, Sara A,Shashwat Sachdev,Arijit Singh", artist: "Saregama Music", ytId: 'GVizJ_jpUnw', lyrics: "" },
    { id: 'h_new_11', title: "Vaaste 8K Video Song: Dhvani B, Siddharth G | Tanishk B,Nikhil D'Souza| Bhushan K| Radhika R,Vinay S", artist: "T-Series", ytId: 'eTl-FnVvGu0', lyrics: "" },
    { id: 'h_new_12', title: "Best Of Arijit Singh Romantic Songs |#arijitsingh #romanticsongs #bestofbest Arijit Singh all Sonng", artist: "Ronak Bhatt", ytId: 'IVjl5u4s-mQ', lyrics: "" },
    { id: 'h_new_13', title: "Sahiba (Official Music Video) : Aditya Rikhari, Ankita Chhetri | T-Series", artist: "T-Series", ytId: 'n2dVFdqMYGA', lyrics: "" },
    { id: 'h_new_14', title: "Lyrical | Saiyaara Title Song | Ahaan, Aneet | Tanishk Bagchi, Faheem Abdullah, Arslan| Irshad Kamil", artist: "YRF", ytId: 'FudfVyYWNxQ', lyrics: "" },
    { id: 'h_new_15', title: "KAUN TUJHE  Lyrical | M.S. DHONI -THE UNTOLD STORY | Amaal Mallik Palak | Sushant Singh Disha Patani", artist: "T-Series", ytId: 'Ov0YGGSY6gY', lyrics: "" },
    { id: 'h_new_16', title: "Non Stop Road Trip Love Hits - Full Album | 3 Hour Non-Stop Romantic Songs | 50 Superhit Love Songs", artist: "Timeless Tunes", ytId: '2lPDqElikDs', lyrics: "" },
    { id: 'h_new_17', title: "KAUN TUJHE 8K Video Song | Armaan Malik | M.S. DHONI -THE UNTOLD STORY | Sushant Singh Rajput", artist: "T-Series", ytId: 'uNboFgKLGDY', lyrics: "" },
    { id: 'h_new_18', title: "Best of Shreya Ghoshal Songs | Tum Kya Mile | Jaadu Hai Nasha | Ve Kamleya | Non-Stop Playlist", artist: "Saregama Music", ytId: 'y0qJKs_rtcE', lyrics: "" },
    { id: 'h_new_19', title: "Lyrical: Tum Hi Aana | Marjaavaan | Riteish D, Sidharth M, Tara S |Jubin Nautiyal,Payal Dev,Kunaal V", artist: "T-Series", ytId: 'tLqtnGLfm4Q', lyrics: "" },
    { id: 'h_new_20', title: "FIGHTER: Mitti (Full Video) Hrithik Roshan, Deepika Padukone, Anil Kapoor | Vishal-Sheykhar", artist: "T-Series", ytId: '9QvzrledPxg', lyrics: "" },
    { id: 'h_new_21', title: "Tere Hawaale (Full Video) Laal Singh Chaddha | Aamir,Kareena | Arijit,Shilpa | Pritam,Amitabh,Advait", artist: "T-Series", ytId: 'KUpwupYj_tY', lyrics: "" },
    { id: 'h_new_22', title: "Best of Vishal Mishra 🎵 2 Hours Non-Stop 🎵 Jaan Ban Gaye, Chal Tere Ishq Mein, Teri Hogaiyaan & More", artist: "Timeless Tunes", ytId: '5XZShg6_tpo', lyrics: "" },
    { id: 'h_new_23', title: "Jogi - Lyrical | Shaadi Mein Zaroor Aana | Rajkummar Rao, Kriti Kharbanda | Arko, Yasser, Aakanksha", artist: "Zee Music Company", ytId: 'HexFqifusOk', lyrics: "" },
    { id: 'h_new_24', title: "LYRICAL: Kaise Hua | Kabir Singh | Shahid K, Kiara A, Sandeep V | Vishal Mishra, Manoj Muntashir", artist: "T-Series", ytId: 'WWXm39leYew', lyrics: "" },
    { id: 'h_new_25', title: "Full Song: Tujhe Kitna Chahne Lage | Kabir Singh | Mithoon Feat. Arijit Singh | Shahid K, Kiara A", artist: "T-Series", ytId: 'AgX2II9si7w', lyrics: "" },
    { id: 'h_new_26', title: "Bekhayali Full Song | Kabir Singh | Shahid K,Kiara A|Sandeep Reddy Vanga | Sachet-Parampara | Irshad", artist: "T-Series", ytId: 'VOLKJJvfAbg', lyrics: "" },
    { id: 'h_new_27', title: "LYRICAL: Tera Ban Jaunga | Kabir Singh | Shahid K, Kiara A, Sandeep V | Tulsi Kumar, Akhil Sachdeva", artist: "T-Series", ytId: 'Qdz5n1Xe5Qo', lyrics: "" },
    { id: 'h_new_28', title: "Full Song: Mere Sohneya | Kabir Singh | Shahid K, Kiara A, Sandeep V | Sachet - Parampara | Irshad K", artist: "T-Series", ytId: 'Njq4A5DAqRw', lyrics: "" },
    { id: 'h_new_29', title: "Kesariya - Brahmāstra | Ranbir Kapoor, Alia Bhatt | Pritam | Arijit Singh | Amitabh Bhattacharya| 4K", artist: "Sony Music India", ytId: 'BddP6PYo2gs', lyrics: "" },
    { id: 'h_new_30', title: "Full Song: KHAIRIYAT (BONUS TRACK) | CHHICHHORE | Sushant, Shraddha | Pritam, Amitabh B|Arijit Singh", artist: "T-Series", ytId: 'hoNb6HuNmU0', lyrics: "" },
    { id: 'h_new_31', title: "FULL SONG: Yeh Aaina | Kabir Singh | Shahid Kapoor, Kiara Advani Nikita D| Amaal Mallik Feat.Shreya", artist: "T-Series", ytId: 'UcOx6Bm3_4k', lyrics: "" },
    { id: 'h_new_32', title: "ANIMAL:Pehle Bhi Main(Full Video) | Ranbir Kapoor,Tripti Dimri |Sandeep V |Vishal M,Raj S |Bhushan K", artist: "T-Series", ytId: 'iAIBF2ngbWY', lyrics: "" },
    { id: 'h_new_33', title: "ANIMAL: SATRANGA(Song) Ranbir Kapoor,Rashmika|Sandeep V|Arijit,Shreyas P,Siddharth-Garima |Bhushan K", artist: "T-Series", ytId: 'HrnrqYxYrbk', lyrics: "" },
    { id: 'h_new_34', title: "ANIMAL: Saari Duniya Jalaa Denge (Film Version) Ranbir K, Bobby D, Sandeep, B Praak,Jaani, Bhushan K", artist: "T-Series", ytId: '6DfaBq2rVoE', lyrics: "" },
    { id: 'h_new_35', title: "ANIMAL: ARJAN VAILLY | Ranbir Kapoor | Sandeep Vanga | Bhupinder B, Manan B | Bhushan K", artist: "T-Series", ytId: 'zqGW6x_5N0k', lyrics: "" },
    { id: 'h_new_36', title: "Best Of Bollywood Dance Hits 8K (Video Jukebox) | Non Stop Bollywood Dance Songs", artist: "T-Series", ytId: 'I0b88L53Gbg', lyrics: "" },
    { id: 'h_new_37', title: "Vaaste Song: Dhvani Bhanushali, Tanishk Bagchi | Nikhil D'Souza | Bhushan Kumar | Radhika R, Vinay S", artist: "T-Series", ytId: 'BBAyRBTfsOU', lyrics: "" },
    { id: 'h_new_38', title: "Jagga Jasoos: Galti Se Mistake Video Song | Ranbir, Katrina | Pritam, Arijit, Amit | Amitabh B", artist: "T-Series", ytId: '05TA9jNnCdU', lyrics: "" },
    { id: 'h_new_39', title: "Give Me Some Sunshine - 3 Idiots | Aamir Khan, Madhavan, Sharman J | Suraj Jagan | Shantanu Moitra", artist: "Zee Music Company", ytId: 'lbCRtrrMvSw', lyrics: "" },
    { id: 'h_new_40', title: "ARIJIT SINGH: Woh Din Lyrical | Chhichhore | Sushant, Shraddha | Pritam, Amitabh", artist: "T-Series", ytId: 'xC1cj9zhh6k', lyrics: "" },
    { id: 'h_new_41', title: "SANAM RE Title  Song FULL VIDEO | Pulkit Samrat, Yami Gautam, Urvashi Rautela | Divya Khosla Kumar", artist: "T-Series", ytId: 'DS-raAyMxl4', lyrics: "" },
    { id: 'h_new_42', title: "Unknown Title", artist: "Unknown Artist", ytId: '4HRC6c5-2lQ', lyrics: "" },
    { id: 'h_new_43', title: "Hua Hain Aaj Pehli Baar FULL VIDEO | SANAM RE | Pulkit Samrat, Urvashi Rautela | Divya Khosla Kumar", artist: "T-Series", ytId: 'DGVJtAHzzDQ', lyrics: "" },
    { id: 'h_new_44', title: "Humsafar (Video) | Varun Dhawan, Alia Bhatt | Akhil Sachdeva | \"Badrinath Ki Dulhania\" | T-Series", artist: "T-Series", ytId: 'jIqRbFQl-ds', lyrics: "" },
    { id: 'h_new_45', title: "Kaash Aisa Hota - Darshan Raval | Official Lyrical Video | Latest Hit Song 2019 | Naushad Khan", artist: "Indie Music Label", ytId: 'CeddFGq6sJ4', lyrics: "" },
    { id: 'h_new_46', title: "Mile Ho Tum - Reprise Version | Neha Kakkar | Tony Kakkar | Fever | Gaurav Jang", artist: "Zee Music Company", ytId: 'N2-HsIYd0Go', lyrics: "" },
    { id: 'h_new_47', title: "The Best Of Neha Kakkar 2021 | Neha Kakkar All Songs | Neha Kakkar 2021", artist: "Best Indian Songs", ytId: 'is3Ia7dF9_U', lyrics: "" },
    { id: 'h_new_48', title: "Diljit Dosanjh - G.O.A.T. (Official Music Video)", artist: "Diljit Dosanjh", ytId: 'cl0a3i2wFcc', lyrics: "" },
    { id: 'h_new_49', title: "EMIWAY - FIRSE MACHAYENGE (OFFICIAL MUSIC VIDEO)", artist: "Emiway Bantai", ytId: 'zaCbuB3w0kg', lyrics: "" },
    { id: 'h_new_50', title: "#Flashup By Knox Artiste | #14SONGSON1BEAT", artist: "Knox Artiste", ytId: 'T5rmd-vKQeM', lyrics: "" },
    { id: 'h_new_51', title: "Afusic - Pal Pal (Official Music Video) Prod. @AliSoomroMusic", artist: "AFUSIC", ytId: '8of5w7RgcTc', lyrics: "" },
    { id: 'h_new_52', title: "MILLIONAIRE SONG (Full Video): @YoYoHoneySingh  | GLORY | BHUSHAN KUMAR", artist: "T-Series", ytId: 'XO8wew38VM8', lyrics: "" },
    { id: 'h_new_53', title: "PAPA RAP SONG | RCR's Tribute To His Father! | Hustle Rap Songs", artist: "KaanPhod Music", ytId: 'IdXyALMFA48', lyrics: "" },
    { id: 'h_new_54', title: "Chhota Don | Srushti Tawade | Hustle 2.0", artist: "KaanPhod Music", ytId: 'pTY6TyUoqjM', lyrics: "" },
    { id: 'h_new_55', title: "Nazz VS Srushti | Nazz, Srushti Tawade | Hustle 2.0", artist: "KaanPhod Music", ytId: '7_TT7jtCJOU', lyrics: "" },
    { id: 'h_new_56', title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill", artist: "Coke Studio Pakistan", ytId: '5Eqb_-j3FDA', lyrics: "" },
    { id: 'h_new_57', title: "Chaudhary - Amit Trivedi feat Mame Khan, Coke Studio @ MTV Season 2", artist: "Coke Studio India ", ytId: '1gukvtH_a3I', lyrics: "" },
];